CREATE SCHEMA IF NOT EXISTS shoppinglist;
USE shoppinglist ;

CREATE TABLE IF NOT EXISTS shoppinglist.lists (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(45) NOT NULL,
  color VARCHAR(45) NOT NULL,
  created_utc TIMESTAMP NOT NULL,
  modified_utc TIMESTAMP NOT NULL,
  PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS shoppinglist.list_items (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  list_id INT UNSIGNED NOT NULL,
  contents VARCHAR(45) NOT NULL,
  priority INT NOT NULL,
  is_checked tinyint(1) NOT NULL DEFAULT 0,
  created_utc TIMESTAMP NOT NULL,
  modified_utc TIMESTAMP NOT NULL,
  PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS shoppinglist.notes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  item_id INT UNSIGNED NOT NULL,
  body VARCHAR(1000) NOT NULL,
  created_utc TIMESTAMP NOT NULL,
  modified_utc TIMESTAMP NOT NULL,
  PRIMARY KEY (id));
